#!/usr/bin/env bash
# solution to task 0
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
FILE_PATH="$1"
IP="$2"
USER="$3"
SSH_KEY="$4"
OPTIONS="StrictHostKeyChecking=no"

scp -o $OPTIONS -i "$SSH_KEY" "$FILE_PATH" "$USER"@"IP":~/
