#!/usr/bin/env bash
# solution to task 1 on web server
sudo apt-get update -y
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
