#!/usr/bin/env bash
# solution to task 1 on web server
apt-get update -y
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
echo "Hello World!" > /var/www/html/index.html
service nginx restart
