#!/usr/bin/env bash
# school file checker
schoollfile="school"
if [ -e $schoollfile ]
then
    if [ -s $schoollfile ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f $schoollfile ]
    then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi
