#!/usr/bin/env bash
# school file checker
schoolfile="school"
if [ -e $schoolfile ]
then
    echo "school file exists"
    if [ -s $schoolfile ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f $schoolfile ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
